// testAll.cpp  (version 2)
// Thorough tests for field.cpp. (about 800 thousand of them)
// THIS FILE WAS GENERATED BY CLAUDE TO ASSIST WITH TESTING PURPOSES
// Build:  make testAll
// Run:    ./testAll        (or: make test)
//
// What it tests:
//   1. Hand-checked cases   expected values worked out by hand
//   2. Exhaustive sweeps    every bit position and every hi/lo pair (both
//                           orders), signed and unsigned, over 44 values
//   3. fieldFits edges      every width 1..32, right at min, max and one past
//   4. Round trips          your functions checked against each other
//   5. Invalid input        off by default, see TEST_INVALID_INPUT below
//


#include <cstdio>
#include <cstdint>
#include <exception>
#include <vector>
#include "field.h"

// Set to 1 to test that bad input (position 32, width 0, etc.) throws.
// The directions don't say what bad input should do, so this is off.
#define TEST_INVALID_INPUT 0

// ============================================================
// Reporting
// ============================================================

static const int MAX_PRINT = 10;   // max failures printed per section

static int totalPass = 0, totalFail = 0;
static int secPass = 0, secFail = 0;

static void beginSection(const char* name) {
    secPass = 0;
    secFail = 0;
    printf("\n== %s ==\n", name);
}

static void endSection() {
    if (secFail > MAX_PRINT)
        printf("  ... %d more failures not shown\n", secFail - MAX_PRINT);
    printf("  %d passed, %d failed\n", secPass, secFail);
}

static void pass() {
    secPass++;
    totalPass++;
}

static void fail(const char* desc, const char* detail) {
    secFail++;
    totalFail++;
    if (secFail <= MAX_PRINT)
        printf("  FAIL  %-44s %s\n", desc, detail);
}

// Runs call(). Passes if it returns expected. Any exception is a FAIL.
template <typename F>
static void expectEq(const char* desc, F call, int expected) {
    char detail[128];
    try {
        int got = call();
        if (got == expected) {
            pass();
            return;
        }
        snprintf(detail, sizeof detail, "got 0x%08x  expected 0x%08x",
                 (unsigned)got, (unsigned)expected);
    } catch (const std::exception& e) {
        snprintf(detail, sizeof detail, "threw: %s", e.what());
    } catch (...) {
        snprintf(detail, sizeof detail, "threw an exception");
    }
    fail(desc, detail);
}

// Runs call(). Passes only if it throws something.
template <typename F>
static void expectThrow(const char* desc, F call) {
    try {
        (void)call();
    } catch (...) {
        pass();
        return;
    }
    fail(desc, "expected an exception, none thrown");
}

#define CHECK(call, expected) \
    expectEq(#call, [&]() { return (call); }, (int)(expected))
#define CHECK_THROWS(call) \
    expectThrow(#call, [&]() { return (call); })

// ============================================================
// Answer key (64-bit math, only used to compute expected values)
// ============================================================

static uint32_t U(int v) { return (uint32_t)v; }
static int toInt(uint64_t x) { return (int)(uint32_t)x; }

static int refGetBit(int v, int p)   { return (int)((U(v) >> p) & 1u); }
static int refSetBit(int v, int p)   { return toInt(U(v) | (1ULL << p)); }
static int refClearBit(int v, int p) { return toInt(U(v) & ~(1ULL << p)); }

static void order(int a, int b, int& hi, int& lo) {
    hi = (a > b) ? a : b;
    lo = (a > b) ? b : a;
}

static int refGetField(int v, int a, int b, int isSigned) {
    int hi, lo;
    order(a, b, hi, lo);
    int w = hi - lo + 1;
    uint64_t f = ((uint64_t)U(v) >> lo) & ((1ULL << w) - 1);
    if (isSigned && ((f >> (w - 1)) & 1))
        return (int)((int64_t)f - (int64_t)(1ULL << w));
    return toInt(f);
}

static int refSetField(int old, int a, int b, int n) {
    int hi, lo;
    order(a, b, hi, lo);
    int w = hi - lo + 1;
    uint64_t mask = ((1ULL << w) - 1) << lo;
    uint64_t r = ((uint64_t)U(old) & ~mask) | (((uint64_t)U(n) << lo) & mask);
    return toInt(r);
}

static void fitsRange(int w, int isSigned, int64_t& lo, int64_t& hi) {
    if (isSigned) {
        lo = -(1LL << (w - 1));
        hi = (1LL << (w - 1)) - 1;
    } else {
        lo = 0;
        hi = (1LL << w) - 1;
    }
}

static int refFits(int v, int w, int isSigned) {
    int64_t lo, hi;
    fitsRange(w, isSigned, lo, hi);
    return (v >= lo && v <= hi) ? 1 : 0;
}

// ============================================================
// Test values
// ============================================================

// Fixed seed, so the "random" values are the same every run.
static uint32_t rngState = 0x2545F491u;
static uint32_t nextRand() {
    rngState ^= rngState << 13;
    rngState ^= rngState >> 17;
    rngState ^= rngState << 5;
    return rngState;
}

static const int FIXED_VALUES[] = {
    0, 1, -1, 2, 437, -437,
    0x7fffffff, (int)0x80000000u, (int)0x80000001u,
    0x55555555, (int)0xaaaaaaaau,
    0x12345678, (int)0x87654321u, (int)0xdeadbeefu,
    0x0000ffff, (int)0xffff0000u, 0x00f00f00, 0x0ff0,
    0x3c00, 0xc400
};

static const int NEW_VALUES[] = {
    0, -1, 1, 5, 437, 0x5a5a5a5a, (int)0x80000000u, 0x12345678
};

// ============================================================
// 1. Hand-checked cases
// ============================================================

static void handGetBit() {
    beginSection("getBit: hand-checked");
    CHECK(getBit(437, 0), 1);
    CHECK(getBit(437, 1), 0);
    CHECK(getBit(437, 2), 1);
    CHECK(getBit(437, 8), 1);
    CHECK(getBit(437, 9), 0);
    CHECK(getBit(0, 5), 0);
    CHECK(getBit(-1, 0), 1);
    CHECK(getBit(-1, 31), 1);
    CHECK(getBit((int)0x80000000u, 31), 1);
    CHECK(getBit((int)0x80000000u, 30), 0);
    CHECK(getBit(1, 31), 0);
    CHECK(getBit(0x55555555, 0), 1);
    CHECK(getBit(0x55555555, 1), 0);
    CHECK(getBit(0x55555555, 30), 1);
    CHECK(getBit(0x55555555, 31), 0);
    CHECK(getBit((int)0xaaaaaaaau, 31), 1);
    CHECK(getBit(0x7fffffff, 31), 0);
    CHECK(getBit(0x7fffffff, 30), 1);
    endSection();
}

static void handSetBit() {
    beginSection("setBit: hand-checked");
    CHECK(setBit(437, 0), 0x1b5);
    CHECK(setBit(437, 1), 0x1b7);
    CHECK(setBit(437, 2), 0x1b5);
    CHECK(setBit(437, 3), 0x1bd);
    CHECK(setBit(437, 9), 0x3b5);
    CHECK(setBit(0, 0), 0x1);
    CHECK(setBit(0, 31), 0x80000000u);
    CHECK(setBit(-1, 17), 0xffffffffu);
    CHECK(setBit((int)0x80000000u, 0), 0x80000001u);
    CHECK(setBit(0x7fffffff, 31), 0xffffffffu);
    CHECK(setBit(0x55555555, 1), 0x55555557);
    endSection();
}

static void handClearBit() {
    beginSection("clearBit: hand-checked");
    CHECK(clearBit(437, 0), 0x1b4);
    CHECK(clearBit(437, 1), 0x1b5);
    CHECK(clearBit(437, 2), 0x1b1);
    CHECK(clearBit(437, 8), 0xb5);
    CHECK(clearBit(-1, 0), 0xfffffffeu);
    CHECK(clearBit(-1, 31), 0x7fffffff);
    CHECK(clearBit((int)0x80000000u, 31), 0x0);
    CHECK(clearBit(0, 5), 0x0);
    CHECK(clearBit(0x55555555, 0), 0x55555554);
    CHECK(clearBit((int)0x80000001u, 0), 0x80000000u);
    endSection();
}

static void handGetField() {
    beginSection("getField: hand-checked");
    // Given examples
    CHECK(getField(437, 2, 0, 0), 0x5);
    CHECK(getField(437, 3, 1, 0), 0x2);
    CHECK(getField(437, 4, 2, 1), 0xfffffffdu);
    // hi and lo swapped
    CHECK(getField(437, 0, 2, 0), 0x5);
    CHECK(getField(437, 2, 4, 1), 0xfffffffdu);
    // Middle fields, signed and unsigned
    CHECK(getField(437, 4, 2, 0), 0x5);
    CHECK(getField(437, 7, 4, 0), 0xb);
    CHECK(getField(437, 7, 4, 1), 0xfffffffbu);
    CHECK(getField(437, 8, 0, 1), 0xffffffb5u);
    CHECK(getField(0x12345678, 11, 4, 1), 0x67);
    // 1-bit fields
    CHECK(getField(437, 0, 0, 0), 0x1);
    CHECK(getField(437, 0, 0, 1), 0xffffffffu);
    CHECK(getField(437, 1, 1, 1), 0x0);
    CHECK(getField((int)0x80000000u, 31, 31, 0), 0x1);
    CHECK(getField((int)0x80000000u, 31, 31, 1), 0xffffffffu);
    // Top and bottom halves
    CHECK(getField((int)0xdeadbeefu, 15, 0, 0), 0xbeef);
    CHECK(getField((int)0xdeadbeefu, 15, 0, 1), 0xffffbeefu);
    CHECK(getField((int)0xdeadbeefu, 31, 16, 0), 0xdead);
    CHECK(getField((int)0xdeadbeefu, 31, 16, 1), 0xffffdeadu);
    CHECK(getField((int)0x87654321u, 31, 24, 0), 0x87);
    CHECK(getField((int)0x87654321u, 31, 24, 1), 0xffffff87u);
    // Full 32-bit fields
    CHECK(getField(-1, 31, 0, 0), 0xffffffffu);
    CHECK(getField(0x12345678, 31, 0, 1), 0x12345678);
    CHECK(getField((int)0x87654321u, 31, 0, 0), 0x87654321u);
    CHECK(getField((int)0x87654321u, 31, 0, 1), 0x87654321u);
    CHECK(getField((int)0xdeadbeefu, 0, 31, 0), 0xdeadbeefu);
    CHECK(getField(0, 10, 3, 1), 0x0);
    // Half precision floats: sign 15, exponent 14..10, fraction 9..0
    CHECK(getField(0xC400, 15, 15, 0), 0x1);    // -4.0
    CHECK(getField(0xC400, 14, 10, 0), 0x11);
    CHECK(getField(0xC400, 9, 0, 0), 0x0);
    CHECK(getField(0x3C00, 14, 10, 0), 0xf);    // 1.0
    CHECK(getField(0xC100, 9, 0, 0), 0x100);    // -2.5
    CHECK(getField(0xC100, 14, 10, 1), 0xfffffff0u);
    CHECK(getField(0x7BFF, 14, 10, 0), 0x1e);   // 65504, largest half
    CHECK(getField(0x7BFF, 9, 0, 0), 0x3ff);
    CHECK(getField(0x7C00, 14, 10, 0), 0x1f);   // infinity
    CHECK(getField(0x3555, 9, 0, 0), 0x155);
    endSection();
}

static void handSetField() {
    beginSection("setField: hand-checked");
    // Given examples
    CHECK(setField(437, 2, 0, 5), 0x1b5);
    CHECK(setField(437, 3, 1, 6), 0x1bd);
    CHECK(setField(437, 4, 2, 7), 0x1bd);
    // hi and lo swapped
    CHECK(setField(437, 1, 3, 6), 0x1bd);
    // newValue wider than the field, only low bits used
    CHECK(setField(437, 3, 1, 0xff), 0x1bf);
    CHECK(setField(0, 7, 4, 0x12345678), 0x80);
    // Negative newValue
    CHECK(setField(0, 3, 0, -1), 0xf);
    CHECK(setField(0, 7, 4, -2), 0xe0);
    // Clearing and keeping neighbors
    CHECK(setField(437, 8, 0, 0), 0x0);
    CHECK(setField(-1, 7, 0, 0), 0xffffff00u);
    CHECK(setField((int)0xffffffffu, 15, 8, 0), 0xffff00ffu);
    CHECK(setField((int)0xdeadbeefu, 15, 0, 0), 0xdead0000u);
    CHECK(setField((int)0xdeadbeefu, 31, 16, 0xcafe), 0xcafebeefu);
    // 1-bit fields
    CHECK(setField(437, 0, 0, 0), 0x1b4);
    CHECK(setField(0, 31, 31, 1), 0x80000000u);
    CHECK(setField(-1, 31, 31, 0), 0x7fffffff);
    // Full 32-bit fields
    CHECK(setField(437, 31, 0, 0x12345678), 0x12345678);
    CHECK(setField(0, 31, 0, -1), 0xffffffffu);
    CHECK(setField(-1, 31, 0, 0), 0x0);
    CHECK(setField(437, 0, 31, 7), 0x7);
    // Half precision: flip 4.0 to -4.0, then build -2.5 from nothing
    CHECK(setField(0x4400, 15, 15, 1), 0xc400);
    CHECK(setField(setField(setField(0, 15, 15, 1), 14, 10, 16), 9, 0, 0x100),
          0xc100);
    endSection();
}

static void handFieldFits() {
    beginSection("fieldFits: hand-checked");
    // Given examples
    CHECK(fieldFits(10, 4, 0), 1);
    CHECK(fieldFits(16, 4, 0), 0);
    CHECK(fieldFits(-8, 4, 1), 1);
    // 4 bits
    CHECK(fieldFits(15, 4, 0), 1);
    CHECK(fieldFits(0, 4, 0), 1);
    CHECK(fieldFits(-1, 4, 0), 0);
    CHECK(fieldFits(7, 4, 1), 1);
    CHECK(fieldFits(8, 4, 1), 0);
    CHECK(fieldFits(-9, 4, 1), 0);
    CHECK(fieldFits(-1, 4, 1), 1);
    // 8 bits
    CHECK(fieldFits(255, 8, 0), 1);
    CHECK(fieldFits(256, 8, 0), 0);
    CHECK(fieldFits(127, 8, 1), 1);
    CHECK(fieldFits(128, 8, 1), 0);
    CHECK(fieldFits(-128, 8, 1), 1);
    CHECK(fieldFits(-129, 8, 1), 0);
    // 1 bit
    CHECK(fieldFits(1, 1, 0), 1);
    CHECK(fieldFits(2, 1, 0), 0);
    CHECK(fieldFits(0, 1, 1), 1);
    CHECK(fieldFits(-1, 1, 1), 1);
    CHECK(fieldFits(1, 1, 1), 0);
    // Wide
    CHECK(fieldFits(0x3fffffff, 31, 1), 1);
    CHECK(fieldFits(0x40000000, 31, 1), 0);
    CHECK(fieldFits(0x7fffffff, 31, 0), 1);
    CHECK(fieldFits(0x7fffffff, 32, 1), 1);
    CHECK(fieldFits((int)0x80000000u, 32, 1), 1);
    CHECK(fieldFits(0, 32, 0), 1);
    endSection();
}

// ============================================================
// 2. Exhaustive sweeps
// ============================================================

static void sweepBits(const std::vector<int>& vals) {
    char d[96];

    beginSection("getBit: every position, 44 values");
    for (int v : vals)
        for (int p = 0; p < 32; p++) {
            snprintf(d, sizeof d, "getBit(0x%08x, %d)", U(v), p);
            expectEq(d, [&]() { return getBit(v, p); }, refGetBit(v, p));
        }
    endSection();

    beginSection("setBit: every position, 44 values");
    for (int v : vals)
        for (int p = 0; p < 32; p++) {
            snprintf(d, sizeof d, "setBit(0x%08x, %d)", U(v), p);
            expectEq(d, [&]() { return setBit(v, p); }, refSetBit(v, p));
        }
    endSection();

    beginSection("clearBit: every position, 44 values");
    for (int v : vals)
        for (int p = 0; p < 32; p++) {
            snprintf(d, sizeof d, "clearBit(0x%08x, %d)", U(v), p);
            expectEq(d, [&]() { return clearBit(v, p); }, refClearBit(v, p));
        }
    endSection();
}

static void sweepGetField(const std::vector<int>& vals) {
    char d[96];
    beginSection("getField: every hi/lo pair, both orders, signed + unsigned");
    for (int v : vals)
        for (int a = 0; a < 32; a++)
            for (int b = 0; b < 32; b++)
                for (int s = 0; s <= 1; s++) {
                    snprintf(d, sizeof d, "getField(0x%08x, %d, %d, %d)",
                             U(v), a, b, s);
                    expectEq(d, [&]() { return getField(v, a, b, s); },
                             refGetField(v, a, b, s));
                }
    endSection();
}

static void sweepSetField(const std::vector<int>& vals) {
    char d[112];
    std::vector<int> news(NEW_VALUES,
                          NEW_VALUES + sizeof NEW_VALUES / sizeof NEW_VALUES[0]);
    news.push_back((int)nextRand());
    news.push_back((int)nextRand());

    beginSection("setField: every hi/lo pair, both orders, 10 new values");
    for (int v : vals)
        for (int a = 0; a < 32; a++)
            for (int b = 0; b < 32; b++)
                for (int n : news) {
                    snprintf(d, sizeof d, "setField(0x%08x, %d, %d, 0x%08x)",
                             U(v), a, b, U(n));
                    expectEq(d, [&]() { return setField(v, a, b, n); },
                             refSetField(v, a, b, n));
                }
    endSection();
}

// ============================================================
// 3. fieldFits at the edges of every width
// ============================================================

static void sweepFieldFits() {
    char d[96];
    beginSection("fieldFits: every width 1..32, at the edges");
    for (int w = 1; w <= 32; w++)
        for (int s = 0; s <= 1; s++) {
            int64_t lo, hi;
            fitsRange(w, s, lo, hi);
            std::vector<int64_t> cands = {
                lo - 1, lo, lo + 1, -1, 0, 1, hi - 1, hi, hi + 1,
                INT32_MIN, INT32_MAX
            };
            // Random values of every size
            for (int i = 0; i < 12; i++) {
                int64_t r = (int32_t)(nextRand() >> (nextRand() % 32));
                cands.push_back(r);
                cands.push_back(-r);
            }
            for (int64_t c : cands) {
                if (c < INT32_MIN || c > INT32_MAX) continue;  // not an int
                int v = (int)c;
                // Negative into 32 unsigned bits is unclear, so skip it.
                if (!s && w == 32 && v < 0) continue;
                snprintf(d, sizeof d, "fieldFits(%d, %d, %d)", v, w, s);
                expectEq(d, [&]() { return fieldFits(v, w, s); },
                         refFits(v, w, s));
            }
        }
    endSection();
}

// ============================================================
// 4. Round trips: functions checked against each other
// ============================================================

static void roundTrips(const std::vector<int>& vals) {
    char d[112];

    beginSection("round trip: bit functions");
    for (int v : vals)
        for (int p = 0; p < 32; p++) {
            snprintf(d, sizeof d, "getBit(setBit(0x%08x, %d)) is 1", U(v), p);
            expectEq(d, [&]() { return getBit(setBit(v, p), p); }, 1);

            snprintf(d, sizeof d, "getBit(clearBit(0x%08x, %d)) is 0", U(v), p);
            expectEq(d, [&]() { return getBit(clearBit(v, p), p); }, 0);

            snprintf(d, sizeof d, "setBit twice same as once (0x%08x, %d)",
                     U(v), p);
            expectEq(d, [&]() {
                return (int)(setBit(setBit(v, p), p) == setBit(v, p));
            }, 1);

            snprintf(d, sizeof d, "clear after set same as clear (0x%08x, %d)",
                     U(v), p);
            expectEq(d, [&]() {
                return (int)(clearBit(setBit(v, p), p) == clearBit(v, p));
            }, 1);
        }
    endSection();

    beginSection("round trip: setField with its own field changes nothing");
    for (int v : vals)
        for (int a = 0; a < 32; a++)
            for (int b = 0; b < 32; b++)
                for (int s = 0; s <= 1; s++) {
                    snprintf(d, sizeof d,
                             "setField(v, %d, %d, getField(..%d)) v=0x%08x",
                             a, b, s, U(v));
                    expectEq(d, [&]() {
                        return setField(v, a, b, getField(v, a, b, s));
                    }, v);
                }
    endSection();

    beginSection("round trip: getField gets back what setField put in");
    for (int v : vals)
        for (int a = 0; a < 32; a++)
            for (int b = 0; b < 32; b++) {
                int n = (int)nextRand();
                int hi, lo;
                order(a, b, hi, lo);
                int w = hi - lo + 1;
                snprintf(d, sizeof d, "getField(setField(0x%08x, %d, %d, 0x%08x))",
                         U(v), a, b, U(n));
                expectEq(d, [&]() {
                    return getField(setField(v, a, b, n), a, b, 0);
                }, refGetField(n, w - 1, 0, 0));
            }
    endSection();

    beginSection("round trip: every extracted field fits its width");
    for (int v : vals)
        for (int a = 0; a < 32; a++)
            for (int b = 0; b < 32; b++)
                for (int s = 0; s <= 1; s++) {
                    int hi, lo;
                    order(a, b, hi, lo);
                    int w = hi - lo + 1;
                    if (!s && w == 32) continue;  // unclear case, skipped
                    snprintf(d, sizeof d,
                             "fieldFits(getField(0x%08x, %d, %d, %d), %d)",
                             U(v), a, b, s, w);
                    expectEq(d, [&]() {
                        return fieldFits(getField(v, a, b, s), w, s);
                    }, 1);
                }
    endSection();
}

// ============================================================
// 5. Invalid input (off by default)
// ============================================================

#if TEST_INVALID_INPUT
static void invalidInput() {
    beginSection("invalid input: should throw");
    // Keep only the ones your field.cpp actually throws on.
    CHECK_THROWS(getBit(437, 32));
    CHECK_THROWS(getBit(437, -1));
    CHECK_THROWS(setBit(437, 32));
    CHECK_THROWS(clearBit(437, -1));
    CHECK_THROWS(getField(437, 32, 0, 0));
    CHECK_THROWS(getField(437, 5, -1, 0));
    CHECK_THROWS(setField(437, 32, 0, 1));
    CHECK_THROWS(fieldFits(5, 0, 0));
    CHECK_THROWS(fieldFits(5, 33, 1));
    endSection();
}
#endif

// ============================================================

int main() {
    std::vector<int> vals(FIXED_VALUES, FIXED_VALUES +
                          sizeof FIXED_VALUES / sizeof FIXED_VALUES[0]);
    for (int i = 0; i < 24; i++) vals.push_back((int)nextRand());

    handGetBit();
    handSetBit();
    handClearBit();
    handGetField();
    handSetField();
    handFieldFits();

    sweepBits(vals);
    sweepGetField(vals);
    sweepSetField(vals);
    sweepFieldFits();

    roundTrips(vals);

#if TEST_INVALID_INPUT
    invalidInput();
#endif

    printf("\n========================================\n");
    printf("TOTAL: %d passed, %d failed\n", totalPass, totalFail);
    puts(totalFail == 0 ? "ALL TESTS PASS" : "SOME TESTS FAILED");
    return totalFail == 0 ? 0 : 1;
}